### ISSUE TITLE
scrollbar position & page position don't update when following page link

### ISSUE THREAD

**Issue by mikewillems** [thierryc/react-fullpage#24]
## Expected Behavior
Scrollbar and page "document" positions track viewport position when a breadcrumb / page anchor is clicked.

## Actual Behavior
Scrollbar position and page position with respect to scrolling stay the same when breadcrumb links are clicked. This prevents scroll from working correctly after button-based navigation.

## Navigator and OS versions
Navigator: Chrome v75.0.3770.142
OS: Win 10 Pro v1809 build 17753.615

**Comment by mikewillems** [comment]
![scrollbar_issue](https://user-images.githubusercontent.com/14206684/62185928-294d5900-b319-11e9-8843-363f6e291da4.png)

**Comment by thierryc** [comment]
Tank you for the feed back. I will take a look. I keep you posted.

**Comment by thierryc** [comment]
Can you try this page ?

https://thierryc.github.io/react-fullpage-example/

**Comment by mikewillems** [comment]
Yep, works great! Nice job!

Procedure = just added a link in Chrome console <a href="#root">go up</a>
on other pages and clicked it. Now updates correctly :)

**Comment by Majkina** [comment]
@thierryc can you please add the example page code to the repo?

**Comment by thierryc** [comment]
it is in the gh-pages branch. 

https://github.com/thierryc/react-fullpage/tree/gh-pages

https://github.com/thierryc/react-fullpage-gh-pages/tree/732ab67b4aa203c05c16aa1b0e9af312acd5eeb4
